# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b606bb0426f57edb96800d2c0ef4baf128e6380ff9ad9a43e57c4a6486d8cabb9404eb0c10a224d71d74f5b4a72ca145230b3bfb578450cd57c72bd0d976dd11

test:
  secret_key_base: 5cc9f73184fd29f6655009c5fd8c8755d25bb4c581ff661c9b7edc2984f030a618af247dfb7c77309f24122e7d3c2a99fdb1d1cc336ebf294515dd2df43a42c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
